//by Fhiz
using OpenMMO;
using OpenMMO.Debugging;
using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace OpenMMO.Debugging
{
	
	/// <summary>
	/// DebugProfile used to hold profiling data generated by a DebugHelper
	/// </summary>
	public partial class DebugProfile
	{
		
		public string name;
		public Stopwatch stopWatch = new Stopwatch();
		
		protected List<long> operations = new List<long>();
		protected long lastOperation;
		protected bool active;
		
		/// <summary>
		/// Constructor used to initialize and start a new DebugProfile using it's name
		/// </summary>
		public DebugProfile(string _name)
		{
			name = _name;
			Restart();
		}
		
		/// <summary>
		/// Stops the current profiling operation and adds it to the list of profiled operations.
		/// </summary>
		public void Stop()
		{
			if (!active) return;
			stopWatch.Stop();
			lastOperation = stopWatch.ElapsedMilliseconds;
			operations.Add(lastOperation);
			active = false;
		}
		
		/// <summary>
		/// Stops and immediately restarts the current profiling operation again.
		/// </summary>
		public void Restart()
		{
			lastOperation = 0;
			stopWatch.Stop();
			Start();
		}
		
		/// <summary>
		/// Clears, stops and resets the current profile so that it can be used again (for something else).
		/// </summary>
		public void Reset(string _name="")
		{
			
			if (!String.IsNullOrWhiteSpace(_name))
				name = _name;
				
			operations.Clear();
			lastOperation = 0;
			stopWatch.Stop();
		}
		
		/// <summary>
		/// Prints the current operation and average operation duration, always stops the current profiling operation as well.
		/// </summary>
		public string Print
		{
			get
			{
				CheckActive();
				return "["+this.GetType().Name+"] '"+name+"' ~"+lastOperation.ToString()+"ms (~"+GetAverage.ToString()+"ms average)";
			}
		}
		
		/// <summary>
		/// Starts the profiling operation. Gets called automatically by Restart.
		/// </summary>
		protected void Start()
		{
			stopWatch.Start();
			active = true;
		}
		
		/// <summary>
		/// Checks if a profiling operation is active and stops it if so (used automatically when printing).
		/// </summary>
		protected void CheckActive()
		{
			if (active)
				Stop();
		}
		
		/// <summary>
		/// Retrieves the average execution time based on all profiled operations.
		/// </summary>
		protected long GetAverage
		{
			get {
				long average = 0;
				foreach (long operation in operations)
					average += operation;
				average /= operations.Count;
				return average;
			}
		}
		
	}

}
